import { chromium } from 'playwright';
const out = process.argv[2];
const b = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const p = await b.newPage({ viewport: { width: 1280, height: 900 } });
await p.goto('http://localhost:5173');
await p.getByRole('tab', { name: /inscri|créer/i }).click().catch(() => {});
await p.fill('#username', 'val' + Math.floor(Math.random() * 1e6));
await p.fill('#password', 'motdepasse123');
await p.click('button.btn.primary');
await p.waitForSelector('.scene', { timeout: 20000 });
await p.waitForTimeout(1500);
await p.screenshot({ path: `${out}/g-village.png`, fullPage: false });
await p.click('.spot-hit >> nth=1');
await p.waitForTimeout(500);
await p.screenshot({ path: `${out}/g-panel.png`, fullPage: true });
await p.getByRole('button', { name: 'Carte' }).first().click();
await p.waitForTimeout(4000);
await p.screenshot({ path: `${out}/g-map.png` });
await p.setViewportSize({ width: 390, height: 844 });
await p.getByRole('button', { name: 'Village' }).first().click();
await p.waitForTimeout(1500);
await p.screenshot({ path: `${out}/g-mobile.png` });
await b.close();
